# Generated by Django 5.2 on 2025-05-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='isActive',
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='Unnamed User', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='userType',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('owner', 'Restaurant Owner'), ('tourist', 'Tourist')], max_length=20, null=True),
        ),
    ]
